openapi: 3.0.0
info:
  title: Pantry Management API
  description: API to manage pantry items and recipes 
  version: 1.0.0
paths:
  /api/ingredients/pantry:
    get:
      summary: Get all pantry items for a user
      responses:
        '200':
          description: List of pantry items
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/Ingredient'
    post:
      summary: Add or update an ingredient in the pantry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ingredient'
      responses:
        '201':
          description: Pantry item added or updated
  /api/recipes/favorites:
    get:
      summary: Get all favorite recipes for a user
      responses:
        '200':
          description: List of favorite recipes
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/FavRecipe'
    post:
      summary: Add a favorite recipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FavRecipe'
      responses:
        '201':
          description: Recipe added to favorites
  /api/recipes/{recipeId}:
    patch:
      summary: Update a favorite recipe
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FavRecipe'
      responses:
        '200':
          description: Recipe updated
    delete:
      summary: Remove a favorite recipe
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Recipe removed
  /api/recipes/shoppingList:
    get:
      summary: Get a user's shopping list
      responses:
        '200':
          description: List of shopping list items
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/ShoppingListItem'
    post:
      summary: Add or update an item in the shopping list
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShoppingListItem'
      responses:
        '201':
          description: Item added to shopping list
  /api/recipes/mealPlan/{date}:
    get:
      summary: Get meal plan for a specific date
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Meal plan for the date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealPlan'
    patch:
      summary: Update meal plan for a specific date
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealPlan'
      responses:
        '200':
          description: Meal plan updated

components:
  schemas:
    Ingredient:
      type: object
      properties:
        quantity:
          type: number
          nullable: true
        units:
          type: string
          nullable: true
        purchaseDate:
          type: string
          format: date
          nullable: true
        expirationDate:
          type: string
          format: date
          nullable: true
        frozen:
          type: boolean
          default: false
    FavRecipe:
      type: object
      properties:
        name:
          type: string
          nullable: true
        ingredients:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Ingredient'
        directions:
          type: string
          nullable: true
        notes:
          type: string
          nullable: true
        planned:
          type: boolean
          default: false
        date:
          type: string
          format: date
          nullable: true
    ShoppingListItem:
      type: object
      properties:
        quantity:
          type: number
          nullable: true
        units:
          type: string
          nullable: true
    MealPlan:
      type: object
      properties:
        breakfast:
          type: string
          nullable: true
        lunch:
          type: string
          nullable: true
        dinner:
          type: string
          nullable: true
        snack:
          type: string
          nullable: true
    Recipe:
      type: object
      properties:
        title:
          type: string
        ingredients:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Ingredient'
        directions:
          type: string
        notes:
          type: string
