openapi: 3.0.0
info:
  title: Recipe API
  description: API to retrieve recipes by their ID
  version: 1.0.0
paths:
  /recipes/{id}:
    get:
      summary: Get a recipe by ID
      description: Retrieve a recipe by its unique identifier.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the recipe.
      responses:
        '200':
          description: Recipe found and returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the recipe
                  name:
                    type: string
                    description: The name of the recipe
                  ingredients:
                    type: array
                    items:
                      type: string
                    description: List of ingredients
                  instructions:
                    type: string
                    description: Cooking instructions for the recipe
        '404':
          description: Recipe not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Recipe not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error fetching recipe"
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: string
          description: The ID of the recipe
        name:
          type: string
          description: The name of the recipe
        ingredients:
          type: array
          items:
            type: string
          description: List of ingredients
        instructions:
          type: string
          description: Cooking instructions for the recipe
