services:
  # nginx reverse proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  # reverse proxy let's encrypt companion
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=panrrachel@gmail.com

  # React frontend
  frontend:
    image: pp-frontend
    container_name: frontend
    restart: always
    environment:
      # host for nginx reverse proxy
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}
      # certificate information for let's encrypt
      - LETSENCRYPT_HOST=${FRONTEND_DOMAIN}
    ports:
      - "80:3000"

  # express backend
  backend:
    image: pp-backend
    container_name: backend
    restart: always
    environment:
      # host for nginx reverse proxy
      - VIRTUAL_HOST=${BACKEND_DOMAIN}
      # certificate information for let's encrypt
      - LETSENCRYPT_HOST=${BACKEND_DOMAIN}
      # firebase config
      - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
      - REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
      - REACT_APP_FIREBASE_DATABASE_URL=${REACT_APP_FIREBASE_DATABASE_URL}
      - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
      - REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
      - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
      - REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}
      - SPOONACULAR_API_KEY=${SPOONACULAR_API_KEY}
      # backend stuff
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "8080:5000"